spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: "auth-service"

  datasource:
    url: ${AUTH_DB_URL}
    username: ${AUTH_DB_USERNAME}
    password: ${AUTH_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/master.yaml
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


logging:
  level:
    org.springframework.boot.context.config: DEBUG
    org.springframework.core.env: DEBUG

JWT_SECRET: ${JWT_SECRET}

